SIM ?= icarus
TOPLEVEL_LANG ?= verilog
VERILOG_SOURCES = ../../ak4619/ak4619.sv \
                  ../../ak4619/i2cinit.sv
MODULE = tb_ak4619

include $(shell cocotb-config --makefiles)/Makefile.sim
