M48
; DRILL file {KiCad (6.0.11)} date Tue 21 Feb 2023 23:01:48
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-21T23:01:48+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.11)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0454
%
G90
G05
T1
X-0.722Y-4.17
X-0.704Y-0.072
X-0.466Y-1.042
X-0.438Y-3.756
X0.516Y-3.224
T0
M30
